version: '3'

services:

  database:
    image: mysql:latest
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'toolbar-database'
    ports:
      - '3306:3306'

  toolbar:
    build: .
    ports:
      - '3003:3003'
    depends_on:
      - 'database'
    command: bash -c '/wait-for-it.sh database:3306 && npm run db:setup && npm run start'



